// <auto-generated />
namespace Bullboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addeddateofeditinginadmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeddateofeditinginadmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111349442_Added date of editing in ad model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
