// <auto-generated />
namespace Bullboard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedcategoriesandsubcategoriesmodelsUpdatedAdmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedcategoriesandsubcategoriesmodelsUpdatedAdmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201704061849108_Added categories and subcategories models. Updated Ad model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
